// <auto-generated />
using System;
using HabitTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HabitTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722081616_LinkHabitCompletionsToConfigurationVersions")]
    partial class LinkHabitCompletionsToConfigurationVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_habits_user_id_is_active");

                    b.ToTable("habits", null, t =>
                        {
                            t.HasCheckConstraint("ck_habits_difficulty", "\"difficulty\" IN ('Easy', 'Medium', 'Hard', 'Elite')");

                            t.HasCheckConstraint("ck_habits_frequency_target_count", "(\"frequency_type\" = 'Daily' AND \"target_count\" = 1)\nOR\n(\"frequency_type\" = 'Weekly' AND \"target_count\" BETWEEN 1 AND 7)");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitAttributeReward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("attribute_type");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer")
                        .HasColumnName("xp_amount");

                    b.HasKey("Id")
                        .HasName("pk_habit_attribute_rewards");

                    b.HasIndex("HabitId", "AttributeType")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_attribute_rewards_habit_id_attribute_type");

                    b.ToTable("habit_attribute_rewards", null, t =>
                        {
                            t.HasCheckConstraint("ck_habit_attribute_rewards_attribute_type", "\"attribute_type\" IN (\n    'Discipline',\n    'Fitness',\n    'Vitality',\n    'Focus',\n    'Mind',\n    'Resilience',\n    'Social',\n    'Purpose'\n)");

                            t.HasCheckConstraint("ck_habit_attribute_rewards_xp_amount", "\"xp_amount\" > 0");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateOnly>("CompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("completed_date");

                    b.Property<Guid>("HabitConfigurationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_configuration_version_id");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habit_completions");

                    b.HasIndex("HabitConfigurationVersionId")
                        .HasDatabaseName("ix_habit_completions_habit_configuration_version_id");

                    b.HasIndex("HabitId", "CompletedDate")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_completions_habit_id_completed_date");

                    b.HasIndex("UserId", "CompletedDate")
                        .HasDatabaseName("ix_habit_completions_user_id_completed_date");

                    b.ToTable("habit_completions", (string)null);
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitConfigurationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_from_date");

                    b.Property<DateOnly?>("EffectiveToDateExclusive")
                        .HasColumnType("date")
                        .HasColumnName("effective_to_date_exclusive");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency_type");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_habit_configuration_versions");

                    b.HasIndex("HabitId")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_configuration_versions_habit_id")
                        .HasFilter("\"effective_to_date_exclusive\" IS NULL");

                    b.HasIndex("HabitId", "EffectiveFromDate")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_configuration_versions_habit_id_effective_from_date");

                    b.HasIndex("HabitId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_configuration_versions_habit_id_version_number");

                    b.ToTable("habit_configuration_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_habit_configuration_versions_difficulty", "\"difficulty\" IN ('Easy', 'Medium', 'Hard', 'Elite')");

                            t.HasCheckConstraint("ck_habit_configuration_versions_effective_date_range", "\"effective_to_date_exclusive\" IS NULL\nOR\n\"effective_to_date_exclusive\" > \"effective_from_date\"");

                            t.HasCheckConstraint("ck_habit_configuration_versions_frequency_target_count", "(\"frequency_type\" = 'Daily' AND \"target_count\" = 1)\nOR\n(\"frequency_type\" = 'Weekly' AND \"target_count\" BETWEEN 1 AND 7)");

                            t.HasCheckConstraint("ck_habit_configuration_versions_version_number", "\"version_number\" >= 1");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.UserAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("attribute_type");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_attributes");

                    b.HasIndex("UserId", "AttributeType")
                        .IsUnique()
                        .HasDatabaseName("ix_user_attributes_user_id_attribute_type");

                    b.ToTable("user_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_attributes_attribute_type", "\"attribute_type\" IN (\n    'Discipline',\n    'Fitness',\n    'Vitality',\n    'Focus',\n    'Mind',\n    'Resilience',\n    'Social',\n    'Purpose'\n)");

                            t.HasCheckConstraint("ck_user_attributes_current_xp", "\"current_xp\" >= 0");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WeekStartsOn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Monday")
                        .HasColumnName("week_starts_on");

                    b.HasKey("Id")
                        .HasName("pk_user_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_settings_user_id");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_settings_week_starts_on", "\"week_starts_on\" IN (\n    'Monday',\n    'Tuesday',\n    'Wednesday',\n    'Thursday',\n    'Friday',\n    'Saturday',\n    'Sunday'\n)");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("attribute_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HabitCompletionId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_completion_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_xp_transactions");

                    b.HasIndex("HabitCompletionId", "AttributeType")
                        .IsUnique()
                        .HasDatabaseName("ix_xp_transactions_habit_completion_id_attribute_type");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_xp_transactions_user_id_created_at_utc");

                    b.ToTable("xp_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_xp_transactions_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_xp_transactions_attribute_type", "\"attribute_type\" IN (\n    'Discipline',\n    'Fitness',\n    'Vitality',\n    'Focus',\n    'Mind',\n    'Resilience',\n    'Social',\n    'Purpose'\n)");
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.Habit", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habits_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitAttributeReward", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.Habit", "Habit")
                        .WithMany("HabitAttributeRewards")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_attribute_rewards_habits_habit_id");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitCompletion", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.HabitConfigurationVersion", "HabitConfigurationVersion")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("HabitConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_habit_completions_habit_configuration_versions_habit_config");

                    b.HasOne("HabitTracker.Api.Domain.Entities.Habit", "Habit")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_completions_habits_habit_id");

                    b.HasOne("HabitTracker.Api.Domain.Entities.User", "User")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_completions_users_user_id");

                    b.Navigation("Habit");

                    b.Navigation("HabitConfigurationVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitConfigurationVersion", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.Habit", "Habit")
                        .WithMany("HabitConfigurationVersions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_configuration_versions_habits_habit_id");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.UserAttribute", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.User", "User")
                        .WithMany("UserAttributes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_attributes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("HabitTracker.Api.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.XpTransaction", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Entities.HabitCompletion", "HabitCompletion")
                        .WithMany("XpTransactions")
                        .HasForeignKey("HabitCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_xp_transactions_habit_completions_habit_completion_id");

                    b.HasOne("HabitTracker.Api.Domain.Entities.User", "User")
                        .WithMany("XpTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_xp_transactions_users_user_id");

                    b.Navigation("HabitCompletion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.Habit", b =>
                {
                    b.Navigation("HabitAttributeRewards");

                    b.Navigation("HabitCompletions");

                    b.Navigation("HabitConfigurationVersions");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitCompletion", b =>
                {
                    b.Navigation("XpTransactions");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.HabitConfigurationVersion", b =>
                {
                    b.Navigation("HabitCompletions");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("HabitCompletions");

                    b.Navigation("Habits");

                    b.Navigation("UserAttributes");

                    b.Navigation("UserSettings")
                        .IsRequired();

                    b.Navigation("XpTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
